### PR TITLE
added: ability to run SPE1 deck as a regression test

### PR DESCRIPTION
**Pull request by akva2**
- you have to pass -DRUN_INTERNAL_TESTS=1
- you have to use 'make check' to pull down the data, not 'make test'
- you need to have your SSH key registered at github since
  it clones opm-data over ssh.

Depends on https://github.com/OPM/opm-cmake/pull/25

### CODE REVIEW

**Comment by atgeirr** [comment]
Thanks for working on this! I would very much like to see this. However, there is a big problem: we cannot and should not depend on the opm-data repo, since it is private. However, the new SPE1 deck created by Lars can be openly licensed, and that (small) file can and should be added to this repo!

I would therefore ask you to rewrite this with that  in mind.

One more thing: you would still *run* the test with `make test`? The `make check` was just to pull the data, right? (Which should not be necessary with the deck included here.)

**Comment by akva2** [comment]
yes, though you should just stop using make test all-together, it's the most broken part of cmake (you cannot add dependencies to the built-in targets).

i will rewrite however you want it, this was just to show you how it can be done and right now the file was there..

**Comment by akva2** [comment]
do note that i use the comparison script from opm-data as well. that also  needs to be relocated.

**Comment by atgeirr** [comment]
> do note that i use the comparison script from opm-data as well. that also needs to be relocated.

That's fine, we can (and should) distribute that.

> yes, though you should just stop using make test all-together, it's the most broken part of cmake (you cannot add dependencies to the built-in targets). check will build tests, run dependent targets and then execute tests. an example: in opm-upscaling, if you use make test you risk comparing to old data if the program crashes. 'make check' however will nuke data prior to running the tests.

Sounds like we should only use 'make check' then. Is the problem that we cannot fix nor remove the 'make test' target?

**Comment by akva2** [comment]
you cannot remove the 'test' target since that's the only way to actually execute the tests using ctest (or well, you could re-do add_test and all that manually but that's way too much work for little gain).

**Comment by akva2** [comment]
as for the data, i cannot do that part of the work, as there is no reference data for the spe1_new directory so there is nothing to compare to. unless it's supposed to compare to spe1 ?

**Comment by atgeirr** [comment]
> as for the data, i cannot do that part of the work, as there is no reference data for the spe1_new directory so there is nothing to compare to. unless it's supposed to compare to spe1

This will be added to opm-data, I am sure, but I had some hope that we could make a useful test without adding any binary data files. Perhaps we cannot? The summary for spe1 is just 18 KB or so, but the restart file (with pressure, saturation fields etc.) is 2.8 MB, and I certainly do not want that in.

**Comment by akva2** [comment]
well that is the data being compared currently. an "opm-public-data" repo seems warranted.

**Comment by atgeirr** [comment]
> an "opm-public-data" repo seems warranted.

I think we had a discussion some time ago on whether this was better suited for a repo or website hosting, I think the worry was that huge binary data files (for Norne for example) is a bad fit for git (even though we sometimes do use it for such things).

**Comment by akva2** [comment]
Would be no problem pulling down from http either

-------- Opprinnelig melding --------
Fra: Atgeirr Flø Rasmussen <notifications@github.com>
Dato: 15.07.2015 16.09 (GMT+01:00)
Til: OPM/opm-autodiff <opm-autodiff@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [opm-autodiff] added: ability to run SPE1 deck as a regression test (#417)


an "opm-public-data" repo seems warranted.

I think we had a discussion some time ago on whether this was better suited for a repo or website hosting, I think the worry was that huge binary data files (for Norne for example) is a bad fit for git (even though we sometimes do use it for such things).

**Comment by alfbr** [comment]
I think we should open up opm-data over summer. Making a repo with public in its name suggests that we have a secret repository. Including history for the NTNU hosted datasets is AFAIK not problematic. Once we have fully replaced them with openly licensed versions, we should simply open up the repository, and ensure that all datasets on opm repos on github are open from there on.

**Comment by atgeirr** [comment]
Since last we visited this, the opm-data repo has indeed been made public, making parts of the discussion above obsolete. There are also tests in opm-parser that use opm-data directly. I think cloning opm-data in the build tree is a bit heavy, the tests in opm-parser depend on finding opm-data locally (is that correct @joakim-hove)? I'd prefer for these two modules to use the same mechanism unless there are good reasons not to.

**Pull request closed without merging**
