### PR TITLE
CPRPreconditioner: make compile with DUNE 2.2.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR restores the compatibility with the DUNE 2.2 version. 

DISCLAIMER: I really DON'T recommend to use DUNE 2.2, since it's relatively old and also slower, i.e. when  running flow on SPE9 and Norne there are significant performance decreases. So use DUNE 2.3.1 instead. I also recommend to not support DUNE 2.2 anymore.

### CODE REVIEW

**Comment by bska** [comment]
> I also recommend to not support DUNE 2.2 anymore.

Noted.  Until such time as we decide we won't support Ubuntu 14.04 LTS that's not really an option however.

**Comment by dr-robertk** [comment]
@bska: How about providing the appropriate DUNE modules (debian packages) along with the new OPM release and by doing so fix the OPM relases to at least this DUNE version and avoid problems and bugs that come up due to different versions of DUNE. That is really hard to keep track of.

**Comment by atgeirr** [comment]
It sounds like a good idea to provide 2.3 packages in our PPA if they are not available from other places, although I hoped that they would be.

**Comment by bska** [comment]
> How about providing the appropriate DUNE modules (debian packages) along with the new OPM release

I suppose we could, but on the other hand I'd **really** prefer if the OPM project not become an upstream source for Dune packages.  At some point we more or less decided that OPM would support stock configurations of the most recently available Ubuntu LTS (14.04 at this time) as well as selected versions of RHEL (currently 5 and 6).  As we are not in a position to retrofit the package set of popular distributions, that means making certain compromises in the features we use as well as being somewhat conservative when updating third-party requirements.

It **also** means that while the goal of supporting the currently active Ubuntu LTS is in effect, the job of the release manager, and by extension the PR reviewers, entails verifying that a given submission does not break any supported configuration.  Yes, that's a big job that could do with automation in a clean environment (&lt;cough&gt;Jenkins&lt;/cough&gt;).

**Comment by atgeirr** [comment]
Thanks for the patch! I assume it has been tested? I'll merge this anyway since we're currently broken, and then we may think about removing 2.2 support until next release.

**Pull request merged**
