### PR TITLE
Test pr builder

### PR DESCRIPTION
**Pull request by akva2**
sorry for the noise..

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins run SPE norne please

**Comment by akva2** [comment]
jenkins run SPE norne please

**Comment by akva2** [comment]
jenkins run SPE norne polymer please

**Comment by akva2** [comment]
jenkins run SPE norne polymer please

**Comment by akva2** [comment]
jenkins run SPE norne polymer please

**Comment by akva2** [comment]
jenkins run SPE norne polymer please

**Comment by akva2** [comment]
jenkins run SPE norne polymer please

**Comment by akva2** [comment]
jenkins run norne polymer please

**Comment by atgeirr** [comment]
Can this be closed now?

**Comment by akva2** [comment]
Yeah forgot one of em..

**Pull request closed without merging**
