### PR TITLE
do not write the results twice per time step

### PR DESCRIPTION
**Pull request by andlaus**
this fixes the problem that the well totals in the summary files are
off by a factor of two...

### CODE REVIEW

**Comment by andlaus** [comment]
okay, I've fixed  this PR for the non-adaptive time-stepping case.

**Comment by atgeirr** [comment]
I'm finally able to take a look at this. There are test failures in the Travis check, could you investigate that @andlaus?

**Comment by andlaus** [comment]
I'll have a look. I guess that this just needs a new reference solution because the well totals change. (obviously, because this is the motivation of this PR.)

**Comment by atgeirr** [comment]
I'll merge this when a PR with new reference solutions is available in opm-data (and I have verified it).

**Comment by andlaus** [comment]
ok. it seems like the test failures were caused by something which is not related to this PR. (after rebasing it on the current master version, they pass on my machine.) Since we now have a nice Jenkins instance:

jenkins build this opm-core=974 please
jenkins run spe please

**Comment by akva2** [comment]
jenkins run spe opm-core=947 please

**Comment by bska** [comment]
> seems like the test failures were caused by something which is not related to this PR.

See #636.

**Comment by akva2** [comment]
see now @andlaus you follow that 'details' link to see job progress (click 'show all checks') ^^^

**Comment by akva2** [comment]
my bad, 947 != 974. please try to trigger it @andlaus (with the correct pr number! :))

**Comment by andlaus** [comment]
> my bad, 947 != 974. please try to trigger it @andlaus (with the correct pr number! :))

is this correct?:

jenkins run spe opm-core=974 please

**Comment by akva2** [comment]
yes, but it did not trigger a build. sigh, i suspect the java re used to match the trigger doesn't run in multiline mode. can you try it in a separate comment without surrounding text. sorry for being my test monkey..

**Comment by andlaus** [comment]
jenkins run spe opm-core=974 please

**Comment by andlaus** [comment]
> sorry for being my test monkey..

no problem, there are worse things :)

**Comment by akva2** [comment]
there we go. i looked into it, the multiline support is actually patched into the kodi builder i was used to working with. i don't want to maintain the builder so we will have to live with the requirement of a separate comment with the trigger.

**Comment by akva2** [comment]
hmm, it did trigger a build but sadly not the one we wanted. i have make some noise again..

**Comment by akva2** [comment]
jenkins run spe opm-core=974 please

**Comment by akva2** [comment]
there we go. stupid java re, i keep doing posix stuff.. now i won't touch it again ;)

**Comment by andlaus** [comment]
ok, on travis this still does not compile and the problem seems to be that it does not find opm-output...

**Comment by bska** [comment]
> on travis this still does not compile and the problem seems to be that it does not find opm-output...

Rebase on top of current master (which includes #636) and that problem will go away.

**Comment by akva2** [comment]
rebase, that's the pr bska pointed to.

**Comment by andlaus** [comment]
> rebase, that's the pr bska pointed to. travis runs the branch as-is.

fun. *arg*

one shenangian in the jenkins test is the last line:

```
Setting status of b17a1b99c51e383449d12d611788bc494c2e6cbd to FAILURE with url http://80.240.129.131:8080/job/opm-autodiff-PR-builder/11/ and message: 'Build finished. 13 tests run, 0 skipped, 0 failed.'
```

it is correct to set the status to FAILURE because some test failed (although I cannot reproduce this locally), but why does it say `13 tests run, 0 skipped, 0 failed.`?

**Comment by akva2** [comment]
tests refer to the unit tests. all 13 of those passed. it fails because the integration test failed (the spe run). those are not included in the ctest output. i can do xml shenanigans to inject the results into the uploaded junit file but then i need some tools which aren't available on the jenkins box.

**Comment by andlaus** [comment]
> tests refer to the unit tests. all 13 of those passed. it fails because the integration test failed (the spe run). those are not included in the ctest output. i can do xml shenanigans to inject the results into the uploaded junit file but then i need some tools which aren't available on the jenkins box.

that's not necessary, at least as far as I am concerned. how can I run these integration tests on my machine to investigate why the error happens?

**Comment by akva2** [comment]
see part two of my email earlier. or just read jenkins/run-spe.sh and replicate manually.

**Comment by andlaus** [comment]
k. thx

**Comment by andlaus** [comment]
weird: the comparison works on my local machine. anyway, let's see if just updating the reference solutions make Jenkins and Travis happy...

**Comment by andlaus** [comment]
jenkins run spe opm-core=974 opm-data=95 please

**Comment by akva2** [comment]
No trigger support for opm data. Didnt consider that it would me most useful to have. will add tmrw!

-------- Opprinnelig melding --------
Fra: Andreas Lauser <notifications@github.com>
Dato: 05.04.2016 17:49 (GMT+01:00)
Til: OPM/opm-autodiff <opm-autodiff@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [OPM/opm-autodiff] do not write the results twice per time step (#613)


jenkins run spe opm-core=974 opm-data=95 please

**Comment by andlaus** [comment]
Ok. Trigger jenkins once you're done. I hope all integration tests pass now.

**Comment by andlaus** [comment]
OPM/opm-output#12 seems to be a more appropriate fix. closing.

**Pull request closed without merging**
