### PR TITLE
ParallelDebugOutput: only use parallel output when mpi size > 1.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR revised the ParallelDebugOutput such that it is only used in parallel simulations.

### CODE REVIEW

**Comment by dr-robertk** [comment]
The last commit fixes the problem with the WelslManager initialization.

**Comment by blattms** [comment]
Great. I can confirm that it does fix the WellsManager issue with the null permeability. 
The original problem described in #483 persists, though.

**Comment by blattms** [comment]
But only for real parallel runs, i.e. more than one process.

**Comment by dr-robertk** [comment]
@blattms: I fixed the problem that you experienced for Norne. Should work now.

**Comment by atgeirr** [comment]
This looks fine to me. Do you consider it merge-ready?

**Comment by dr-robertk** [comment]
I'll double check with @blattms.

**Comment by dr-robertk** [comment]
It's ok to merge.

**Pull request merged**
