### PR TITLE
Replaced SimulatorState -> SimulationDataContainer

### PR DESCRIPTION
**Pull request by joakim-hove**
OK - I know think this is ready for a review; would also like to run the Norne case before merge. Will post here when that is done.

This still applies: https://github.com/OPM/opm-autodiff/issues/601

### CODE REVIEW

**Comment by joakim-hove** [comment]
Ahhhh - sorry; I have made some git f... up here. Will update the branches later today.

**Comment by joakim-hove** [comment]
OK Norne is green.

**Comment by atgeirr** [comment]
> OK Norne is green.

I assume that means results and runtimes are identical with or without these patches?

**Comment by joakim-hove** [comment]
Results  - runtime noe checked.
11. mars 2016 09:00 skrev "Atgeirr Flø Rasmussen" <notifications@github.com>
følgende:

**Comment by joakim-hove** [comment]
ping?

**Comment by atgeirr** [comment]
> ping?

On it.

**Comment by atgeirr** [comment]
Preliminary performance tests seem to indicate significant increase in runtime with this PR (about 25% increase). I will double check this in case I did something wrong, and do some profiling.

**Comment by joakim-hove** [comment]
> Preliminary performance tests seem to indicate significant increase in runtime with this PR (about 25% increase)

Whoha - if this turns out be correct I am *veeery* suprised  - and disappointed. Please post further findings.

**Comment by atgeirr** [comment]
I can confirm the speed penalty. It also seems clear that to blame are the slow convenience functions like pressure(), saturation() etc. They used to be fast and inlineable (reducing I guess often to just pointer usage), but are no longer. So code like (from BlackoilModelBase::updateState()):
```
        // Update the reservoir_state
        for (int c = 0; c < nc; ++c) {
            reservoir_state.saturation()[c*np + pu.phase_pos[ Water ]] = sw[c];
        }
```
will be very slow. One could argue that code like the one above is based on faulty assumptions (that accessing reservoir_state.saturation() is just as fast as using an alias), but it used to be true, and therefore we should try to avoid changing it. Otherwise we'd have to hunt for code parts like above, and also make sure no-one writes code like that again. I'd say it is easier to provide a fast implementation of saturation() etc. then.

**Comment by atgeirr** [comment]
Two more notes:
 - The implementation can be much like the current SimulatorState class.
 - There may be other significant performance problems with this, that I have not seen yet (but I doubt it).

**Comment by joakim-hove** [comment]
> I'd say it is easier to provide a fast implementation of saturation() etc. then.

Ehhh - my expectation was that we should remove these special case `saturation()`, `pressure()` and so on anyways. My strong suggestion would be to:

1. Remove the `.pressure()` and `.saturation()` methods.
2. Update the call sites:

```C++
// Update the reservoir_state
for (int c = 0; c < nc; ++c) {
    reservoir_state.saturation()[c*np + pu.phase_pos[ Water ]] = sw[c];
}
```

```C++
// Update the reservoir_state
{
   auto& saturation = reservoir_state.getCellData( "SATURATION" );
   for (int c = 0; c < nc; ++c) {
       saturation[c*np + pu.phase_pos[ Water ]] = sw[c];
   }
}
```

Alternatives: 

1. The PR's can be updated to remove `.saturation()` and `.pressure()` before merging.
2. The PR's for removing `.saturation()` and `.pressure()` can be created on top of the current branches - and then merged afterwards.

> [...] but it used to be true, and therefore we should try to avoid changing it

I do not think that is a good argument; if we want to move forward we must make changes. 

> The implementation can be much like the current SimulatorState class.

???

**Comment by atgeirr** [comment]
The proposed change to client code is much less convenient than what we have. The purpose of these PRs in my opinion is to have a generic interface that can be used by the output facilities, and there is no reason to remove those methods since it does not stand in the way of the main goal.

When I say that the implementation can be like the current SimulatorState class it is because it does manage to provide both a generic interface and fast, custom accessors.

**Comment by bska** [comment]
> My strong suggestion would be to:
>
> 1. Remove the `.pressure()` and `.saturation()` methods.
> 2. Update the call sites

Yes, please.  I'd even suggest going one step further:
```C++
auto& saturation = // ...
auto* Sw = &saturation[0*np + pu.phase_pos[Water]];

for (int c = 0; c < nc; ++c, Sw += np) {
    Sw[c] = sw[c];
}
```

**Comment by joakim-hove** [comment]
> The proposed change to client code is much less convenient than what we have.

Well - that is in the mind of the beholder; IMHO the proposed change is more explicit and easier on the eyes.

> it does manage to provide both a generic interface and fast, custom accessors.

Well that I disagree - with special functions `.pressure()` and `.saturation()` is *not* very generic.

**Comment by dr-robertk** [comment]
In the mean time to avoid performance decrease you could keep an
internal reference in SimulationDataContainer that is returned in
saturation() and pressure().

**Comment by joakim-hove** [comment]
> In the mean time to avoid performance decrease you could keep an
internal reference in SimulationDataContainer that is returned in
saturation() and pressure().

I will do that - as a *temporary* measure.

**Comment by joakim-hove** [comment]
> I will do that - as a temporary measure.

https://github.com/OPM/opm-common/pull/87

**Comment by jokva** [comment]
The convenience functions pressure etc. can still be made inlinable (and probably should) via the `inline` keyword. Unfortunately this also means that the implementation details must be available in all translation units that wants to use the call, but since they're somewhat trivial this shouldn't matter too much in terms of compilation times (and the run-time benefit certainly outweighs the drawback here).

**Comment by atgeirr** [comment]
> The convenience functions pressure etc. can still be made inlinable (and probably should) via the inline keyword.

I think it quite probably *is* inlined in the current PR, I was maybe inaccurate earlier. The performance killer is probably the lookup being done every call, inline or not.

**Pull request merged**
