### PR TITLE
roughly write the messages to log file.

### PR DESCRIPTION
**Pull request by qilicun**

### CODE REVIEW

**Comment by joakim-hove** [comment]
Currently `OPM_ERROR` and `OpmLog` are both in `opm-common` - would it not be natural that the `OPM_ERROR` macro is extended with a call to `OpmLog::error()`?

**Comment by qilicun** [comment]
>Currently OPM_ERROR and OpmLog are both in opm-common - would it not be natural that the OPM_ERROR macro is extended with a call to OpmLog::error()

That is possible, but to be clear to the user, I think keep them for developer would be much better.

**Comment by atgeirr** [comment]
I think that we should add the logging call to OPM_THROW, instead of adding lots of OpmLog::error() everywhere. Before going further with the approach proposed here I'd like us to agree how we want this to look in the code (in the short term). Some alternatives:

1. Replace existing OPM_THROW() with OpmLog::error() and make OpmLog::error throw.
2. Add an OpmLog::error() statement to the OPM_THROW macro.
3. Do it as in this PR: both OpmLog::error() and OPM_THROW at each site.

I think number 3 is too inconvenient, it reduces readability and increases the risk of forgetting to do one of the two things.

Number 1 is a little inconvenient, too: the macro allows us to use streaming operators in the message such as
```
OPM_THROW(std::runtime_error, "Control mode type " << mode << " not present in well " << well_names[well_index]);
```
In general it is less convenient if we must pass a string (in the macro, a stringstream is used to build the string). That is lost if we go with number 1.

Therefore I think we should go with number 2. Perhaps we should rename OPM_THROW to OPM_ERROR at the same time?

In the longer term we may want to have similar macros for OPM_INFO, OPM_WARNING etc. What do you think?

**Comment by qilicun** [comment]
To be clarified, currently most of the messages are related to **developer**, fewer of them are related to **user**(who actually run the simulator with deck), that 3 ways will write all the messages to the log file, the user will be confused. In this PR, just some of the message write to the log file which  are closely related to the user,  I think this messages can help them understanding the error in deck file.

**Comment by joakim-hove** [comment]
My comments:

1. I suggest going with Atgeirr suggestion 2.
2. We should stick to OPM_THROW,  not OPM_ERROR
3. Not necessary to make OPM_INFO,  but maybe Opm::info should be a macro.

**Comment by atgeirr** [comment]
I see your point. Although if an exception is thrown that causes the simulator to stop, that should certainly be in the log file. I admit it is not obvious what should happen in the case of exceptions that will be caught, but I think that too should find its way to the log file in some form (for example if the linear solver fails so we cut the time step).

In conclusion I think we should not separate the two: throwing and logging an error.

**Comment by atgeirr** [comment]
> Not necessary to make OPM_INFO, but maybe Opm::info should be a macro

That would mix the worlds of macros and functions in how they look, I think macros should be OPM_MACRONAME.

**Comment by atgeirr** [comment]
It looks like the consensus is to add OpmLog::error() to the OPM_THROW macro. I'll therefore close this PR.

**Pull request closed without merging**
