### PR TITLE
Removes unused experimental header include to fix build.

### PR DESCRIPTION
**Pull request by blattms**
The include of ParallelRestrictedAdditiveSchwarz.hh was a left over
from some experiments and should not be here yet.

### CODE REVIEW

**Comment by bska** [comment]
Thanks.  While you're here, would you mind updating the `CMakeLists_files.txt` file too to account for the new file `opm/autodiff/AdditionalObjectDeleter.hpp`?

**Comment by blattms** [comment]
@bska Done.

**Comment by bska** [comment]
> Done.

Thanks, much appreciated. I'll just do a local build test and then I'll merge unless anything comes up.

**Comment by bska** [comment]
> I'll just do a local build test and then I'll merge unless anything comes up.

Everything is rosy.  Thanks a lot for the prompt response and the great work on parallelisation.

**Pull request merged**
