### PR TITLE
Moving the StandardWells class definition to separate files. 

### PR DESCRIPTION
**Pull request by GitPaean**
Tested with Flow (Norne did not finish running),  Flow_solvent, Flow_polymer and Flow_multisegment.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by bska** [comment]
jenkins run spe polymer norne please

**Comment by GitPaean** [comment]
I am not sure if the following test failure is relevant. 
```
IndexError: list index out of range
Build step 'Execute shell' marked build as failure
Skipped archiving because build is not successful
Recording test results
No JDK named ?null? found
No JDK named ?null? found
Setting status of 2a89650bbe25b15daf0c1595e1dfecb061b2a38d to FAILURE with url http://80.240.129.131:8080/job/opm-autodiff-PR-builder/17/ and message: 'Build finished. 13 tests run, 0 skipped, 0 failed.'
No JDK named ?null? found
Finished: FAILURE
```

But the residual history for Norne running did change during the past few days (maybe yesterday).

**Comment by akva2** [comment]
jenkins run polymer norne please

**Comment by akva2** [comment]
spe is broken, and it's not related to this PR.

**Comment by GitPaean** [comment]
Is the `please` part of the grammar to trigger Jenkins or just something related to good manners?

**Comment by akva2** [comment]
hehe. it's in the regular expression. it can be removed as such but jenkins is sweating for us, so i think being polite is only fair.

**Comment by atgeirr** [comment]
Good, another small but important step. Merging.

**Pull request merged**
