### PR TITLE
Import opm-polymer into opm-autodiff

### PR DESCRIPTION
**Pull request by akva2**
This

- imports opm-polymer into opm-autodiff (retaining all history).
- integrates opm-polymer into the opm-autodiff buildsystem

For reference; I
1) made a fresh clone of opm-polymer
2) ran git filter-branch -f --tree-filter "rm -rf cmake debian doc redhat dune.module CMakeLists_files.cmake CMakeLists.txt configure CTestConfig.cmake dune.module" --prune-empty HEAD
3) merged the resulting repositories into opm-autodiff (git pull &lt;path_to_repo&gt;)
4) moved the opm-polymer test from examples/ to test/
5) updated the buildsystem

### CODE REVIEW

**Comment by atgeirr** [comment]
Thanks a lot, @akva2! I will try out this and merge it if successful.

**Comment by bska** [comment]
> Thanks a lot, @akva2!

Yeah, massive effort.  Can I just add one small, stylistic request?  I'd really prefer if all the file lists in `CMakeLists_files.cmake` (cf. akva2/opm-autodiff/@c6410d0) were indented by a single `<tab>` character.

**Comment by akva2** [comment]
i just imported the block from polymer verbatim. will change.

**Comment by atgeirr** [comment]
> were indented by a single <tab> character.

Would this be a good time to change this long-running convention to (finally) use spaces here as well?

**Comment by akva2** [comment]
done.

**Comment by akva2** [comment]
let's do that separately.

**Comment by atgeirr** [comment]
> let's do that separately.

Changing to spaces, I assume you mean? Doing it later is ok. I am not sure we have a consensus on the issue though?

**Comment by akva2** [comment]
yes, sorry for not quoting. that's why i suggest putting it off for later. if you ask me, tabs must die.

**Comment by atgeirr** [comment]
It compiles, and all files present are identical to the current master versions of the respective repositories, so I will merge now. Thanks!

**Pull request merged**
