### PR TITLE
Autodiff matrix types

### PR DESCRIPTION
**Pull request by babrodtk**
This significantly improves performance of flow by keeping track of matrix types. The gist of it is that if a is zero, identity or a purely diagonal matrix, we can use specialized multiplication/addition/etc. methods that are faster than a general sparse (op) sparse method.

Tested that it gives same result as master.

### CODE REVIEW

**Comment by totto82** [comment]
I get the following error when I try to build this branch
>type 'Opm::AutoDiffMatrix' is not  a direct base of 'Opm::AutoDiffMatrix' 
line 109 in AutoDiffMatrix.hpp 
Everything seems to work fine if I just remove the : AutoDiffMatrix() from line 109 

When I run it without line 109 it gives approx 5% speedup for norne.

**Comment by atgeirr** [comment]
Your error is due to too old compiler, not supporting delegate constructors. Without the line in question, the source of the move operation gets filled with uninitialized garbage instead of default-initialised.

I had hoped for more than 5% though...

**Comment by dr-robertk** [comment]
Looks good, nice work. I tested SPE9 and I can run it in 25 sec where I had used 39 sec before the summer. The improvement might not be solely due to this PR though but who cares. I'm running Norne and that also looks good but needs some time to finish (still ;-)). 

I have a few comments on the code. There is now the type Eigen::SparseMatirx<double> all over the place and I would like to see this as a central typedef (like before, maybe AutoDiffMatrix::Sparse ???) so that exchange of the matrix type or the scalar (eg from double to float) is gonna be easy. 
It doesn't have to be M or S because that's hard to read (and find). 

I'll post my final comments this afternoon.

**Comment by atgeirr** [comment]
> I saw this on a couple of places and I'm just wondering why += is not possible to be implemented? Is it more efficient this way?

The initial implementation of AutoDiffMatrix did not have +=, but I think we should implement it.

**Comment by atgeirr** [comment]
> There is now the type Eigen::SparseMatirx all over the place and I would like to see this as a central typedef (like before, maybe AutoDiffMatrix::Sparse ???) so that exchange of the matrix type or the scalar (eg from double to float) is gonna be easy. 
> It doesn't have to be M or S because that's hard to read (and find).

The AutoDiffMatrix::Sparse typedef already exists, but I am a little reluctant to use it everywhere:
 - Some functions use Eigen-specific interfaces (such as setFromTriplets()), there I think it is better to be explicit about Eigen usage (but double vs floats and row vs. column ordering could be handled).
 - Some functions are like specifically written to handle cases involving Eigen::SparseMatrix (such as the specific operator*), I think those are more easy to grasp if that type is used explicitly.

I think that the "AutoDiffBlock::M" typedef was used a little too much, perhaps we have now gone too far in the other direction... If you have a concrete example or two of where you'd like to see a change I am willing to rewrite.

**Comment by dr-robertk** [comment]
It's my allergy against using the same type everywhere without a typedef. typedefs are essential for easy-to-maintain software because changes require only a few places to change things. 

I just completed Norne. Looks very good. I'm now down to a factor of 3.5 compared to ecl 2014.2, that is to say I can run Norne in <  1 hour. I haven't checked the results though. I will do so after lunsj.

**Comment by dr-robertk** [comment]
From my point of view this is good to go. Flow compiles and SPE9 and Norne run without problems.

**Comment by dr-robertk** [comment]
One more thing, to make the code compile for @totto82 I suggest to simply repeat the initialization of the variables in the constructor taking the rvalue reference. When this is implemented the green button can be pushed.

**Comment by atgeirr** [comment]
Thanks for the review, merging.

**Comment by bska** [comment]
> Thanks for the review, merging.

This breaks the build in downstream module opm-polymer (
```
/var/lib/jenkins/workspace/opm-polymer/opm/polymer/fullyimplicit/PolymerPropsAd.cpp: In member function ‘Opm::ADB Opm::PolymerPropsAd::effectiveInvWaterVisc(const ADB&, const double*) const’:
/var/lib/jenkins/workspace/opm-polymer/opm/polymer/fullyimplicit/PolymerPropsAd.cpp:182:47: error: conversion from ‘Eigen::SparseMatrix<double>’ to non-scalar type ‘Opm::AutoDiffBlock<double>::M {aka Opm::AutoDiffMatrix}’ requested
         ADB::M dim_diag = spdiag(dinv_mu_w_eff);
                                               ^
/var/lib/jenkins/workspace/opm-polymer/opm/polymer/fullyimplicit/PolymerPropsAd.cpp: In member function ‘Opm::ADB Opm::PolymerPropsAd::polymerWaterVelocityRatio(const ADB&) const’:
/var/lib/jenkins/workspace/opm-polymer/opm/polymer/fullyimplicit/PolymerPropsAd.cpp:229:37: error: conversion from ‘Eigen::SparseMatrix<double>’ to non-scalar type ‘Opm::AutoDiffBlock<double>::M {aka Opm::AutoDiffMatrix}’ requested
         ADB::M dmc_diag = spdiag(dmc);
                                     ^
/var/lib/jenkins/workspace/opm-polymer/opm/polymer/fullyimplicit/PolymerPropsAd.cpp: In member function ‘Opm::ADB Opm::PolymerPropsAd::adsorption(const ADB&, const ADB&) const’:
/var/lib/jenkins/workspace/opm-polymer/opm/polymer/fullyimplicit/PolymerPropsAd.cpp:277:39: error: conversion from ‘Eigen::SparseMatrix<double>’ to non-scalar type ‘Opm::AutoDiffBlock<double>::M {aka Opm::AutoDiffMatrix}’ requested
         ADB::M dads_diag = spdiag(dads);
                                       ^
make[2]: *** [CMakeFiles/opmpolymer.dir/opm/polymer/fullyimplicit/PolymerPropsAd.cpp.o] Error 1
make[1]: *** [CMakeFiles/opmpolymer.dir/all] Error 2
make: *** [all] Error 2
Build step 'Execute managed script' marked build as failure
Finished: FAILURE
```

**Comment by atgeirr** [comment]
Oops, I will fix.

**Pull request merged**
