### PR TITLE
Save PRT in the same folder as summary file.

### PR DESCRIPTION
**Pull request by qilicun**

### CODE REVIEW

**Comment by atgeirr** [comment]
I guess this is a "give engineers what they expect" thing? I am (still) a bit uneasy about ignoring the output_dir and writing to the base case dir, but we want to avoid surprising people. @alfbr?

**Comment by qilicun** [comment]
Output_dir still exits, this PR just moves LOGFILE(.PRT file )out of that folder.

**Comment by atgeirr** [comment]
Sorry for taking so long, I now know how I want this to work:
 - if output_dir is *not* specified in the parameters, write in the base dir (as this PR does), opm-specific stuff still defaults to be written to a dir called "output"
 - if output_dir *is* specified, that should be used instead (as before this PR).
This is consistent with the way all other eclipse-type output is handled (restart, summary etc), by EclipseWriter. You can implement this behaviour like this:
```
if (param_.has("output_dir")) {
    logFile_ = output_dir_ + "/" + baseName + ".PRT"; 
} else {
    logFile_ = baseName + ".PRT";
}
```

**Comment by qilicun** [comment]
PR is updated, travis error is``could not find opm-output``.

**Comment by atgeirr** [comment]
Looks good, will merge!

**Pull request merged**
