### PR TITLE
Autodiffmatrix beautification

### PR DESCRIPTION
**Pull request by babrodtk**
This PR adds documentation to AutoDiffMatrix, and changes the how to create an identity matrix.

### CODE REVIEW

**Comment by atgeirr** [comment]
This is not mergeable now, and may also be in conflict with #485.

**Comment by babrodtk** [comment]
Should be mergeable now

**Comment by bska** [comment]
> Should be mergeable now

It is, at least from the point of view of introducing no regressions.  Everything builds and all tests pass.

**Comment by atgeirr** [comment]
Thanks for the patch, and for the build check. I'll merge!

**Pull request merged**
